AI Debate app Demo
unifyai/demos pull request #10
Opened 2024-05-21 05:32 UTC by Sanjay8602

Description
This pull request introduces a new Streamlit application, AI Debate App, to the existing repository of UnifyAI demos.
Debate-App is a web application that enables a back-and-forth conversation between two Language Models (LLMs) on a topic chosen by the user. Users can select any two models, input a query, and visualize the dialogue between the LLMs in real-time.

Changes
New Files: Added all necessary files for the Debate app, including app.py, requirements.txt, and related assets.

Updated Documentation: Included detailed instructions in the README.md within the AI Debate App directory, outlining how to set up and run the application locally and how to access the hosted version.

Demo Video: Link of demo video is attached in the README file of this PR for better visualization
All the folders or files have been added in Unify

2024-05-21 08:37 UTC, hello-fri-end requested changes

2024-05-21 08:37 UTC, hello-fri-end commented on Unify/LLM_Debate/Readme.MD
> +</video>
You're still not following the instructions mentioned in the [template](https://github.com/unifyai/demos/blob/main/template/README_TEMPLATE.md?plain=1#L1-L9). Can you also checkout this [example](https://github.com/unifyai/demos/blob/main/Unify/LLM-Wars/README.md?plain=1#L1-L7) if the template is not clear?

Specifically, you need to place the video folder in the root directory and assets folder.

2024-05-21 08:37 UTC, hello-fri-end commented on Unify/LLM_Debate/Readme.MD
> +[demo] (https://github.com/Sanjay8602/demo/assets/121057369/8f98d746-e1f2-497a-b2e2-ecd43e29674b)
```suggestion
[demo](https://github.com/Sanjay8602/demo/assets/121057369/8f98d746-e1f2-497a-b2e2-ecd43e29674b)
```

2024-05-21 11:04 UTC, Sanjay8602 commented on Unify/LLM_Debate/Readme.MD
> +</video>
I have change from my account to unify account and link working properly

2024-05-23 10:16 UTC, hello-fri-end commented on Unify/LLM_Debate/Readme.MD
> +</video>
Please look at [this](https://github.com/unifyai/demos/blob/main/Unify/LLM-Wars/README.md?plain=1#L5) again and update accordingly. Thanks!

2024-05-27 19:48 UTC, Sanjay8602 commented
Can u help regarding static_ format in my  file. Because in folder I dont have any static follder?

2024-05-28 07:25 UTC, Sanjay8602 reviewed
changed to static

2024-05-31 07:31 UTC, merged