Misc fixes
unifyai/demos pull request #46
Opened 2023-08-16 16:16 UTC by rishabgit

2023-08-17 14:41 UTC, guillesanbri requested changes

2023-08-17 14:41 UTC, guillesanbri commented on examples_and_demos/mmpretrain_to_jax.ipynb
> +        "As expected, we have made the model significantly faster with just one line of code! Latency gets even better on V100 GPU - rocking 2-3x improvement in speed-up! 🚀"
maybe a bit less informal is better, i.e. `Latency gets even better on a V100 GPU, where we can get up to a 2-3x increase in execution speed! 🚀`

2023-08-18 08:31 UTC, rishabgit commented
@guillesanbri quick reminder on this :smile:

2023-08-18 09:12 UTC, guillesanbri approved these changes

2023-08-18 09:13 UTC, merged