Enabling demos tests with nightly binaries
unifyai/demos pull request #68
Opened 2023-11-09 06:55 UTC by vedpatwardhan

2023-11-09 08:45 UTC, vedpatwardhan commented
Hey @Dsantra92, here's an [example](https://github.com/unifyai/demos/actions/runs/6809112110) workflow with the nightly binaries, you'd need to go to the workflow page, select the branch as `demos_tests_nightly` (as we're yet to merge the PR) and pass "true" for the "Testing with nightly binaries : " field as shown in the image to trigger the workflow with the nightly binaries. Let me know if there's any changes to be made, thanks 😄
<img width="1470" alt="Screenshot 2023-11-09 at 2 12 53 PM" src="https://github.com/unifyai/demos/assets/54766411/ecfba7b6-e7d6-4b02-81b9-9dc03439b875">

2023-11-12 23:58 UTC, Dsantra92 requested changes
Some basic formatting changes. Otherwise LGTM.

2023-11-12 23:58 UTC, Dsantra92 commented on .github/workflows/_basic-test.yml
> +        required: false
Are we removing the option for workflow_dispatch? Also can make the nightly_binaries type boolean, that seems more consistent?

2023-11-12 23:58 UTC, Dsantra92 commented on .github/workflows/_demo-test.yml
> +        required: false
Same as the review on .github/workflows/_basic-test.yml

2023-11-12 23:58 UTC, Dsantra92 commented on .github/workflows/run-test-suite.yml
> +        description: 'Testing with nightly binaries :'
We should add the type here.

2023-11-12 23:58 UTC, Dsantra92 commented on tests/test_demos.sh
> +if [ $3 == "true" ];
Sorry to nitpick on the formatting, lol:
```suggestion
if [ "$3" == "true" ]; then
    export VERSION=nightly
fi
```

2023-11-13 04:30 UTC, vedpatwardhan commented on .github/workflows/_basic-test.yml
> +        required: false
actually the `workflow_dispatch` type is already present for the `run-test-suite` which calls these workflows anyway. Do you think we should have a `workflow_dispatch` for this workflow as well?
Sure, I'll change the type to `boolean` 👍

2023-11-13 04:30 UTC, vedpatwardhan commented on .github/workflows/run-test-suite.yml
> +        description: 'Testing with nightly binaries :'
Sure, I'll add it 👍

2023-11-13 04:30 UTC, vedpatwardhan commented on tests/test_demos.sh
> +if [ $3 == "true" ];
no worries at all, it's actually better to format it that way 👍

2023-11-13 04:41 UTC, vedpatwardhan commented on tests/test_demos.sh
> +if [ $3 == "true" ];
done

2023-11-13 04:41 UTC, vedpatwardhan commented on .github/workflows/run-test-suite.yml
> +        description: 'Testing with nightly binaries :'
done

2023-11-13 04:41 UTC, vedpatwardhan commented on .github/workflows/_demo-test.yml
> +        required: false
done

2023-11-13 04:42 UTC, vedpatwardhan commented on .github/workflows/_basic-test.yml
> +        required: false
done changing the type to `boolean`, let me know if you'd like a `workflow_dispatch` to `_basic-test`. Cuz for `_demos-test` we'd need `run-test-suite` as it needs to start the vm before running it and stop the vm after running `_demos-test`

2023-11-13 04:47 UTC, Dsantra92 commented on .github/workflows/_basic-test.yml
> +        required: false
Yeah, I think that would too much of hassle for now. Moreover I don't think there will be cases where we need to run these seperately.

2023-11-13 04:50 UTC, Dsantra92 requested changes

2023-11-13 04:50 UTC, Dsantra92 commented on tests/test_demos.sh
> +if [ "$3" ]; then
This will still be a string comparison. The value of $3 is string as it passed to bash script.

2023-11-13 05:17 UTC, vedpatwardhan commented on tests/test_demos.sh
> +if [ "$3" ]; then
oh shoot, just made a change, let me know if that sounds good, thanks!

2023-11-13 17:58 UTC, Dsantra92 approved these changes

2023-11-13 17:59 UTC, Dsantra92 commented
LGTM. Feel free to merge when it's ready @vedpatwardhan.

2023-11-14 05:21 UTC, vedpatwardhan commented
Awesome, thanks @Dsantra92 😄
Also, I saw a `nightly` branch on the `ivy` repo as well just like the `binaries` repo, do you want the demos tests running using the `nightly` branch binaries to also use the `ivy` repo's `nightly` branch?

2023-11-14 13:34 UTC, Dsantra92 commented
Yep, we would need the ivy nightly branch. Otherwise new binaries and function definitions wouldn't work.

2023-11-14 14:35 UTC, vedpatwardhan commented
> Yep, we would need the ivy nightly branch. Otherwise new binaries and function definitions wouldn't work.

done, I'll merge the PR now, but there seems to be an additional test failure in the nightly branch with the [torch_to_jax](https://github.com/unifyai/demos/actions/runs/6864778182/job/18667351003) demo as compared to the current code and binaries. I'd suggest looking into that issue before merging the nightly binaries into main. Thanks @Dsantra92 😄

2023-11-14 14:36 UTC, merged