Chatbot Arena streamlit app
unifyai/demos pull request #7
Opened 2024-05-09 08:57 UTC by Kacper-W-Kozdon

This pull request is from the fork, not the main repo. *The main repo can be found here:* https://github.com/samthakur587/LLM_playground
When samthakur makes all the necessary updates in the main repo, the contents of the PR will get replaced. The deployed app linked to the *forked repo* can be found here: https://llm-playground-unify.streamlit.app/

2024-05-09 09:00 UTC, Kacper-W-Kozdon commented
@hello-fri-end a pull request from the fork. Once the main repo (from samthakur) is updated, it can be swapped, since samthakur prepared all of the docker files and a lot of configs (and they might steel need some updates for the image to work 100%)

2024-05-12 17:43 UTC, hello-fri-end requested changes
Hey @Kacper-W-Kozdon ! Thank you for making this contribution :muscle: :rocket: . I moved the demo video section to the top in the [template readme](https://github.com/unifyai/demos/blob/main/template/README_TEMPLATE.md) to  better catch the attention of the viewer. Could you please look at the changes and update the README please?  You can take a look the [README of LLM-Wars project](https://github.com/unifyai/demos/blob/main/Unify/LLM-Wars/README.md?plain=1) for an example.  Happy to review again once you're done! :)

P.S could you please uncommit the __pycache__ folder please?

2024-05-12 18:38 UTC, hello-fri-end requested changes
Hey @Kacper-W-Kozdon, thanks for making the changes. Could you please move the `test`, `pages` and `utils` folders inside the `ChatBot Arena` folder. Thanks!

Also, looks like the README still isn't updated, maybe you forgot to push the changes :smile: Happy to review again once you're done!

2024-05-12 18:53 UTC, Kacper-W-Kozdon commented
> Hey @Kacper-W-Kozdon, thanks for making the changes. Could you please move the `test`, `pages` and `utils` folders inside the `ChatBot Arena` folder. Thanks!
> 
> Also, looks like the README still isn't updated, maybe you forgot to push the changes 😄 Happy to review again once you're done!

Video moved to the top 👍

2024-05-13 05:32 UTC, hello-fri-end requested changes
Hey @Kacper-W-Kozdon, you need to pull the latest changes from the repo and add your demo video to the Videos folder as mentioned [here](https://github.com/unifyai/demos/blob/main/template/README_TEMPLATE.md?plain=1#L4-L10). Also, I'd suggest removing the image from the README, it feels kinda repetitive given that we have already added a video demo.

2024-05-13 05:40 UTC, hello-fri-end requested changes
Hey @Kacper-W-Kozdon! Just left a couple of comments, after which this should be good to merge. 

P.S take a look at [this](https://unify.ai/docs/demos/demos/Unify/LLM-Wars/README.html) to get an idea of how the README should render on our docs. Thanks!

2024-05-13 05:40 UTC, hello-fri-end commented on Unify/Chatbot Arena/README.md
> +<p align="center">
Let's remove the image. The video should be enough :)

2024-05-13 05:40 UTC, hello-fri-end commented on Unify/Chatbot Arena/README.md
> +<hr>
Can we remove this as well? All the demos on our docs should follow the same [template](https://github.com/unifyai/demos/blob/main/template/README_TEMPLATE.md?plain=1#L4-L10). Feel free to keep it in your fork of the project tho :)

2024-05-13 05:40 UTC, hello-fri-end commented on Unify/Chatbot Arena/README.md
> +    ├── __init__.py
Same as above. It's best not to include this in the docs.

2024-05-13 05:40 UTC, hello-fri-end commented on Unify/Chatbot Arena/README.md
> +   git checkout -b new-feature-x
Same as above. It's not super critical for the docs.

2024-05-13 05:40 UTC, hello-fri-end commented on Unify/Chatbot Arena/README.md
> +
same as above.

2024-05-13 05:40 UTC, hello-fri-end commented on Unify/Chatbot Arena/README.md
> +
Can you add this in a table like mentioned in the README template. Thanks!

2024-05-13 05:40 UTC, hello-fri-end commented on Unify/Chatbot Arena/README.md
> +---
Let's remove this.

2024-05-13 09:25 UTC, Kacper-W-Kozdon commented on Unify/Chatbot Arena/README.md
> +<p align="center">
👍

2024-05-13 09:25 UTC, Kacper-W-Kozdon commented on Unify/Chatbot Arena/README.md
> +    ├── __init__.py
👍

2024-05-13 09:25 UTC, Kacper-W-Kozdon commented on Unify/Chatbot Arena/README.md
> +   git checkout -b new-feature-x
👍

2024-05-13 09:26 UTC, Kacper-W-Kozdon commented on Unify/Chatbot Arena/README.md
> +
👍

2024-05-13 09:26 UTC, Kacper-W-Kozdon commented on Unify/Chatbot Arena/README.md
> +---
👍

2024-05-13 10:14 UTC, hello-fri-end requested changes

2024-05-13 10:14 UTC, hello-fri-end commented on Unify/Chatbot Arena/README.md
> +https://github.com/Kacper-W-Kozdon/demos-Unify/assets/102428159/8ed6ae60-4005-4557-bc8f-154c1a4d58c7
Can you please thoroughly go through the instructions [here](https://github.com/unifyai/demos/blob/main/template/README_TEMPLATE.md?plain=1#L1-L11).  Here's an [example](https://github.com/unifyai/demos/blob/main/Unify/LLM-Wars/README.md?plain=1#L4C1-L7C9).

2024-05-13 11:22 UTC, Kacper-W-Kozdon commented on Unify/Chatbot Arena/README.md
> +https://github.com/Kacper-W-Kozdon/demos-Unify/assets/102428159/8ed6ae60-4005-4557-bc8f-154c1a4d58c7
Done 👍

2024-05-13 11:52 UTC, hello-fri-end commented on Unify/Chatbot_Arena/README.md
> +## Introduction
```suggestion
```

2024-05-13 11:53 UTC, hello-fri-end commented on Unify/Chatbot_Arena/README.md
> + 2. [streamlit](https://streamlit.io/)
```suggestion

```

2024-05-13 11:55 UTC, hello-fri-end commented
LGTM! 🚀 🔥 Thanks for the contribution 💪

2024-05-13 11:55 UTC, merged