Semantic Router uploaded project files
unifyai/demos pull request #8
Opened 2024-05-11 12:12 UTC by ithanigaikumar

Uploaded all the files used for the Semantic Router application

2024-05-12 17:41 UTC, hello-fri-end requested changes
Hey @ithanigaikumar ! Thank you for making this contribution :muscle: :rocket: . I moved the demo video section to the top in the [template readme](https://github.com/unifyai/demos/blob/main/template/README_TEMPLATE.md) to  better catch the attention of the viewer. Could you please look at the changes and update the README?  You can take a look the [README of LLM-Wars project](https://github.com/unifyai/demos/blob/main/Unify/LLM-Wars/README.md?plain=1) for an example.  Happy to review again once you're done! :)

2024-05-12 22:57 UTC, ithanigaikumar commented
@hello-fri-end Thank you I have embedded the video first now

2024-05-13 05:46 UTC, hello-fri-end requested changes

2024-05-13 05:46 UTC, hello-fri-end commented on Unify/SemanticRouter/README.md
> +[Demo](https://github.com/unifyai/demos/blob/0be2009315c9a11347cf03d02c9dba394d7afd0e/videos/semanticroutervideo.mp4)
You should drag the video from your local storage to the README. Doing so will generate a link that you should put here. Currently, the video isn't embedded into the README. Hope that makes sense :)

2024-05-13 05:46 UTC, hello-fri-end commented on Unify/SemanticRouter/README.md
> +This streamlit application dynamically routes user queries to the most appropriate model based on semantic similarity.User queries are sent to predefined routes of maths or coding or users have the o
```suggestion
This Streamit application dynamically routes user queries to the most appropriate model based on semantic similarity. User queries are sent to predefined routes of maths or coding or users have the option to create their own custom route. This optimizes output quality while minimizing the cost.
```
Can you elaborate this please?

2024-05-13 05:46 UTC, hello-fri-end commented on Unify/SemanticRouter/README.md
> +| Jeyabalan Nadar               | jeyabalang      |
Can you convert the user-names to links?

2024-05-13 10:14 UTC, ithanigaikumar commented on Unify/SemanticRouter/README.md
> +[Demo](https://github.com/unifyai/demos/blob/0be2009315c9a11347cf03d02c9dba394d7afd0e/videos/semanticroutervideo.mp4)
@hello-fri-end Hi I've tried doing this but it says my file size is too big,even after compressing it?I am a bit confused by this step : /  I made a youtube video so i could put that in instead?

2024-05-13 10:16 UTC, hello-fri-end commented on Unify/SemanticRouter/README.md
> +[Demo](https://github.com/unifyai/demos/blob/0be2009315c9a11347cf03d02c9dba394d7afd0e/videos/semanticroutervideo.mp4)
Oh, what's the duration & size in mb of the video you're trying to upload?

2024-05-13 10:29 UTC, ithanigaikumar commented on Unify/SemanticRouter/README.md
> +[Demo](https://github.com/unifyai/demos/blob/0be2009315c9a11347cf03d02c9dba394d7afd0e/videos/semanticroutervideo.mp4)
@hello-fri-end it was 254,000MB and about 3 minutes long but i put it through the compressor about 3 more times and managed to get a link haha, please could you check if everything is okay to be merged now : )?

2024-05-13 11:35 UTC, hello-fri-end requested changes

2024-05-13 11:35 UTC, hello-fri-end commented on Unify/SemanticRouter/README.md
> +  <source src="https://raw.githubusercontent.com/unifyai/demos/0be2009315c9a11347cf03d02c9dba394d7afd0e/videos/semanticroutervideo.mp4" type="video/mp4">
Hey @ithanigaikumar, the `src` here is not correct. Can you take a look at the instructions [here](https://github.com/unifyai/demos/blob/main/template/README_TEMPLATE.md?plain=1#L4-L10)? Here's an example.

2024-05-13 11:45 UTC, ithanigaikumar commented on Unify/SemanticRouter/README.md
> +  <source src="https://raw.githubusercontent.com/unifyai/demos/0be2009315c9a11347cf03d02c9dba394d7afd0e/videos/semanticroutervideo.mp4" type="video/mp4">
@hello-fri-end okay I've changed it is it correct now?

2024-05-13 15:33 UTC, merged

2024-05-13 15:33 UTC, hello-fri-end commented
LGTM! Thanks for the contribution @ithanigaikumar ! :100: