feat: Add Contributor Demos README file
unifyai/demos pull request #87
Opened 2024-02-27 09:56 UTC by NripeshN

2024-02-28 05:45 UTC, vedpatwardhan requested changes
Hey @NripeshN, just requested a few changes, thanks 😄

2024-02-28 05:45 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +Welcome to the Contributor Demos section of our `unifyai/demos` repository! This initiative is designed to foster collaboration and innovation within our community, allowing individuals and teams to
let's remove "initiative", "innovation", "allowing", etc. it sounds a bit over the top. Probably something like "This folder contains the exciting ML demos that our community created using `ivy`" as the second sentence might sound better. Let's also replace "participate" by "get involved"

2024-02-28 05:45 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +Before diving into the code, we ask all interested participants to fill out a short form. This form captures essential information such as your name, email, and whether you plan to contribute individ
participants --> contributors. Also, we should mention that we're also accepting project preferences in the form, and how they'd be communicated about their group details. As for individuals, we should also mention that they don't need to fill-in any preferences and can work on whatever they want.

2024-02-28 05:45 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +Once you've submitted the form, you're ready to start! Choose from one of the ten projects listed in our [Github Projects](https://github.com/orgs/unifyai/projects/18). Each project comes with a uniq
As discussed, let's add the sections about setting up, generating API keys, etc. before the section about working on the task. We can remove the last sentence here as we're taking the project preferences from them through the form anyway. Let's also mention how they can get in touch with us if they face issues while working on the task, the discord group chats, the weekly calls, other possible calls we'd want to have (not sure exactly about the structure), etc.

2024-02-28 05:45 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +After developing your solution, it's time to submit a Pull Request (PR) to the `unifyai/demos` repository. Make sure to link the specific issue you're addressing by including `closes <#issue no>.` in
We should probably be more clear about what the "solution" looks like. Like a self-contained notebook with comments, some examples of such notebooks (pick a few well-structured ones from kaggle, etc.

2024-02-28 05:45 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +To streamline the review process and facilitate badge awarding, we require a uniform format for PR descriptions. Please include the GitHub IDs of all team members involved in the project at the end o
Let's explicitly mention what individuals are su[p

2024-02-28 05:45 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +- **Single PR Acceptance:** For each issue, only one PR will be merged. We encourage collaboration and communication within the community to combine efforts and submit the best possible solution.
This should probably be one of the first few sections as it's about what's in it for them

2024-02-28 05:45 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +- **Rising Contributors:** Contributors of the merged PR will be immediately promoted to [Rising Contributors](https://unify.ai/docs/ivy/overview/contributing/volunteer_program.html#rising-contributo
let's remove "immediately promoted" and have something like "We're happy to welcome the contributors of the merged PR as Rising contributors in our community" as the first sentence, and probably remove the second sentence as the docs page is already linked

2024-02-28 05:45 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +- Ensure your code is well-documented and follows best practices for readability and maintainability.
A few links about what well-documented and best practices look like

2024-02-28 05:45 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +If you have any questions or need clarification on the process, please feel free to ask us on our [discord server](https://discord.gg/sg2QRAvY). We're here to support you throughout your contribution
there's a few more places in the README where we should have details about what to do when facing issues, etc.

2024-03-07 12:37 UTC, vedpatwardhan requested changes
Just requested a few changes, thanks @NripeshN 😄

2024-03-07 12:37 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +5. Create a virtual environment and install ivy:
Let's add a link to the setting up section of the docs as well, cuz people may not always want to use `venv`

2024-03-07 12:37 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +After developing your solution, it's time to submit a Pull Request (PR) to the `unifyai/demos` repository. Make sure to link the specific issue you're addressing by including `closes <#issue no>.` in
> We should probably be more clear about what the "solution" looks like. Like a self-contained notebook with comments, some examples of such notebooks (pick a few well-structured ones from kaggle, etc.

This needs to be addressed, unless it's already done in the video

2024-03-07 12:37 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +To streamline the review process and facilitate badge awarding, we require a uniform format for PR descriptions. Please include the GitHub IDs of all team members involved in the project at the end o
> Let's explicitly mention what individuals are supposed to do on the PR

This needs to be addressed to avoid confusion, just half a sentence like individuals should add their github ids on the PR sounds good

2024-03-07 12:37 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +- **Single PR Acceptance:** For each issue, only one PR will be merged. We encourage collaboration and communication within the community to combine efforts and submit the best possible solution.
> This should probably be one of the first few sections as it's about what's in it for them

This needs to be addressed, as it's the main value add for them (getting elevated to a rising contributor)

2024-03-07 12:37 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +- Ensure your code is well-documented and follows best practices for readability and maintainability.
> A few links about what well-documented and best practices look like

Still needs to be addressed, unless it's mentioned in the video already

2024-03-08 12:26 UTC, NripeshN commented on Contributor_demos/README.MD
> +After developing your solution, it's time to submit a Pull Request (PR) to the `unifyai/demos` repository. Make sure to link the specific issue you're addressing by including `closes <#issue no>.` in
We have done this in the Video

2024-03-08 12:27 UTC, NripeshN commented on Contributor_demos/README.MD
> +- Ensure your code is well-documented and follows best practices for readability and maintainability.
Already mentioned in the video

2024-03-08 12:30 UTC, NripeshN commented on Contributor_demos/README.MD
> +To streamline the review process and facilitate badge awarding, we require a uniform format for PR descriptions. Please include the GitHub IDs of all team members involved in the project at the end o
I don't get what you mean

2024-03-11 05:14 UTC, vedpatwardhan approved these changes
lgtm! Feel free to merge the PR, thanks @NripeshN 😄

2024-03-11 05:14 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +To streamline the review process and facilitate badge awarding, we require a uniform format for PR descriptions. Please include the GitHub IDs of all team members involved in the project at the end o
nvm, I was just referring to a line that says that individuals don't need to do this, but I think that's implied anyway so let's leave that for now

2024-03-11 05:14 UTC, vedpatwardhan commented on Contributor_demos/README.MD
> +- Ensure your code is well-documented and follows best practices for readability and maintainability.
sounds good!

2024-03-11 07:18 UTC, merged